# Generated by Django 4.2.7 on 2024-11-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_analyzer', '0003_remove_vehiclecount_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecount',
            name='speed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vehiclecount',
            name='confidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vehiclecount',
            name='frame_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehiclecount',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('bus', 'Bus'), ('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle')], max_length=20),
        ),
    ]
