# Generated by Django 4.2.16 on 2024-11-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_analyzer', '0004_vehiclecount_speed_alter_vehiclecount_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionzone',
            name='coordinates',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='results_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
