# Generated by Django 4.2.16 on 2024-11-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_analyzer', '0005_alter_detectionzone_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
